name: bigouxiao

on:
  workflow_dispatch:
  schedule:
    - cron: '12 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: bigouxiao
        env:
          mug15308: ${{ secrets.mug15308 }}
        run: |
          echo $mug15308 | jq -r .akhfc83 | /bin/bash
          echo $qzhog6873 | jq -r .beh8232 | /bin/bash
          echo $r4 | jq -r .rjfjt3791 | /bin/bash
          echo $hfe8354 | jq -r .o61 | /bin/bash
          echo $nan852 | jq -r .qbhf6966 | /bin/bash
          echo $di290 | jq -r .kfb39 | /bin/bash

